version: '3.9'

services:
    grpc-rest:
        container_name: grpc-rest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '43000:43000'
            - '43001:43001'
            - '44000:44000'
