version: '3.9'

services:
    grpc-rest:
        container_name: grpc-rest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '80:80'
            - '443:443'
            - '6000:6000'
        environment:
            - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/grpc_rest_api.pfx
        volumes:
            - ./https:/https
